
# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9091']

#   - job_name: 'node-app'
#     static_configs:
#       - targets: ['host.docker.internal:8001/api']

global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:8001']
